Digital Workspace (73)	</BR>				
ADV1045BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1045BU.mp4">Horizon Cloud on Microsoft Azure: Technical Deep Dive</A></BR>
ADV1076BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1076BU.mp4">Troubleshooting Your Horizon 7 Deployment</A></BR>
ADV1084BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1084BU.mp4">Monitoring Your Horizon Deployments and Users with the Horizon Service</A></BR>
ADV1110BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1110BU.mp4">Architecting Workspace ONE: The Official Reference Architecture</A></BR>
ADV1111BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1111BU.mp4"> Architecting Horizon: The Official Reference Architecture</A></BR>
ADV1227BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1227BU.mp4">Case Study: Making It Epic ??? A Journey to Success</A></BR>
ADV1298BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1298BU.mp4">Advantage: Admin. How VDI Administrators Can Make Everyone Happy  </A></BR>
ADV1299BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1299BU.mp4">Employing a CPA: How Cloud Pod Architecture Redefines DR and Experiences </A></BR>
ADV1300BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1300BU.mp4">One Is Not Enough: Multi-Cloud Deployments Enhance Colleague Experiences</A></BR>
ADV1313BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1313BU.mp4">NSX-T and Horizon: Better Security and Performance for VDI</A></BR>
ADV1322BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1322BU.mp4">How to Template a Non-Persistent VDI Solution for Your Enterprise</A></BR>
ADV1337BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1337BU.mp4">Beyond the Marketing:  What's New in Horizon 7</A></BR>
ADV1483BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1483BU.mp4">Free Your Horizon to Soar in the Clouds</A></BR>
ADV1581BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1581BU.mp4">The Latest and Greatest with VMware Blast Extreme</A></BR>
ADV1583BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1583BU.mp4">Horizon Cloud Services: Reduce Cost and Complexity in Horizon Deployments</A></BR>
ADV1640BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1640BU.mp4">New era of Desktop and App-as-a-Service with VMware and Microsoft Windows Virtual Desktop </A></BR>
ADV1761BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1761BU.mp4">Zero Trust Security with Horizon</A></BR>
ADV1798BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1798BU.mp4">Unified Access Gateway: Securing Virtual Desktop and App Access</A></BR>
ADV1819BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1819BU.mp4">Increase IT Efficiency with a Tailored Application Deployment Strategy</A></BR>
ADV1954BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV1954BU.mp4">Facing the Top 10 Villains of Horizon Cloud</A></BR>
ADV2243BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV2243BU.mp4">Horizon 7 with VMware Cloud on AWS Deployment Architectures</A></BR>
ADV2272BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV2272BU.mp4">The (Not So) Dark Art of Application Packaging and Profiling</A></BR>
ADV2485BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV2485BU.mp4">VMware EUC as a Force for Good</A></BR>
ADV2511BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV2511BU.mp4">Horizon Delivery Models: A Modernized Approach to Desktops and Apps</A></BR>
ADV2549BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV2549BU.mp4">Horizon and NSX - A Match made in Heaven</A></BR>
ADV2668BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV2668BU.mp4">Comprehensive architectural overview and deep-dive troubleshooting on UAG</A></BR>
ADV2808BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV2808BU.mp4">Horizon Disaster Recovery and Cloud Burst to VMware Cloud on AWS: A Case Study</A></BR>
ADV2902BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV2902BU.mp4">Horizon View Upgrades: A Relaxing Experience</A></BR>
ADV3037BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV3037BU.mp4">JMP: The Easy Button for Delivering Virtual Desktops and Apps from Cloud</A></BR>
ADV3410BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV3410BUS.mp4">Size and Configure Horizon to support Professional Graphics Applications</A></BR>
ADV3758BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV3758BUS.mp4">Case Study: How Memorial Hermann Transformed Their End-User Computing Experience</A></BR>
ADV5151BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/ADV5151BU.mp4">Increasing Business Agility with Citrix VDI with VMware Cloud on AWS</A></BR>
DEE1020BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE1020BU.mp4">How to Architect VMware Identity Manager</A></BR>
DEE1807BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE1807BU.mp4">Streamline Your Mobile App Development Lifecycle with the Workspace ONE SDK</A></BR>
DEE2023BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE2023BU.mp4">Workspace ONE and Azure AD Integration: Deep Dive from the Trenches</A></BR>
DEE2174BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE2174BU.mp4"> Best Practices to Succeed in Your Digital Workplace Project</A></BR>
DEE2294BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE2294BU.mp4">Zero Trust ??? Easily achieved with Workspace ONE Access (formerly Identity Manager</A></BR>
DEE2301BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE2301BU.mp4">What???s New: Revolutionize Employee Productivity with Mobile Flows and Intelligent Hub</A></BR>
DEE2391BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE2391BU.mp4">Enable the Full Workspace ONE Intelligent Hub Experience to Drive Digital Transformation</A></BR>
DEE2495BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE2495BU.mp4">Enabling strong authentication for Workspace ONE: Improve security and user experience</A></BR>
DEE2774BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE2774BU.mp4">"Demystifying Enterprise Apps: Secure Deployment, Access, and Management"</A></BR>
DEE2965BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE2965BU.mp4">How to use Workspace ONE to transform your Employee Experience from Onboarding all the way to Offboarding</A></BR>
DEE3015BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE3015BU.mp4">Enabling AI-Powered Workspace ONE Digital Assistant in Intelligent Hub</A></BR>
DEE3022BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE3022BU.mp4">"What's New with Workspace ONE Boxer, Web, Notebook, and Content?"</A></BR>
DEE3094BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/DEE3094BU.mp4">A Customer Success-Driven Blueprint for Workspace ONE Adoption</A></BR>
DEE3477BU <A HREF="NO DOWNLOAD POSTED">Delivering Modern Management Capabilities with Workspace ONE</A></BR>
DEE4398BUS<A HREF="NO DOWNLOAD POSTED">The shift towards employee experience</A></BR>
UEM1063BU<A HREF="NO DOWNLOAD POSTED">How to Architect and Deploy Workspace ONE Assist Remote Support</A></BR>
UEM1438BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM1438BU.mp4">Opportunity Knocks! Support All Enterprise Endpoints by Extending Workspace ONE</A></BR>
UEM1454BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM1454BU.mp4">Workspace ONE AirLift: Get to Windows 10 Modern Management Faster</A></BR>
UEM1455BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM1455BU.mp4">Not Just Physical: Workspace ONE UEM Management of Horizon VDI</A></BR>
UEM1460BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM1460BU.mp4">Windows 10 Troubleshooting Tips and Tricks</A></BR>
UEM1558BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM1558BU.mp4">How to Design a Zero-Trust Architecture Using Workspace ONE</A></BR>
UEM1570BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM1570BU.mp4">Mastering the Move to Windows 10 Modern Management with Workspace ONE</A></BR>
UEM1789BU<A HREF="NO DOWNLOAD POSTED">Enhance User and Device Security Posture with Workspace ONE Intelligence</A></BR>
UEM1810BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM1810BU.mp4">Jump-Start Device Administrator to Android Enterprise Migration</A></BR>
UEM1856BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM1856BU.mp4">"Workspace ONE Intelligence ??? Automation, Dashboards and Reports Introduction"</A></BR>
UEM1929BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM1929BU.mp4">Migrating Your Workspace ONE Deployment to the Cloud</A></BR>
UEM2038BU<A HREF="NO DOWNLOAD POSTED">Risk Analytics: The Next Step in Securing the Digital Workspace</A></BR>
UEM2099BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM2099BU.mp4">Live Demo - macOS Management from Zero to ONE</A></BR>
UEM2155BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM2155BU.mp4">Security Takes a Village: Leveraging Workspace ONE Trust Network</A></BR>
UEM2262BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM2262BU.mp4">Deep(er) Dive into Enterprise iOS Management </A></BR>
UEM2263BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM2263BU.mp4">Make Zero-Touch Provisioning on Windows 10 a Reality for Your Organization</A></BR>
UEM2350BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM2350BU.mp4">Getting the Most Out of Microsoft 365 and Workspace ONE Together</A></BR>
UEM2505BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM2505BU.mp4">Leveraging In-Product Support for Workspace ONE UEM</A></BR>
UEM2679BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM2679BU.mp4">Take This Job and Love It:  Make the Most of Your UEM Solution with Dell Technologies and VMware</A></BR>
UEM2684BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM2684BU.mp4">Upgrade Unlocked: Fusing Intelligent Automation with Proactive Support </A></BR>
UEM2912BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM2912BU.mp4">Workspace ONE Data Loss Prevention Technical Overview </A></BR>
UEM2988BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM2988BU.mp4">Android Enterprise: Modernize Your Rugged Deployments</A></BR>
UEM3009BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM3009BU.mp4">What???s New with Workspace ONE?</A></BR>
UEM3121BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM3121BU.mp4">Employee Experience Management for the Modern Workplace</A></BR>
UEM3592BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM3592BUS.mp4">BeyondCorp: a new approach to enterprise security</A></BR>
UEM3675BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/UEM3675BUS.mp4">"Juggling Okta, Workspace ONE, and Office 365"</A></BR>
</P>					
Emerging Trends (39)	</BR>				
EIOT2688BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/EIOT2688BU.mp4">Chitale: VMware Pulse IoT Center Automates a Leading Dairy Factory in India</A></BR>
EIOT2715BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/EIOT2715BU.mp4">Edge Computing Innovations in Office of the CTO and Dell Technologies</A></BR>
EIOT2750BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/EIOT2750BU.mp4">Extend Your Hybrid Cloud Strategy to the Edge with VMware Edge Solutions</A></BR>
EIOT3138BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/EIOT3138BU.mp4">Introducing Pulse IoT Center 2.0</A></BR>
EIOT3144BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/EIOT3144BU.mp4">How to Drive Measurable Business Value with IoT</A></BR>
EIOT3152BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/EIOT3152BU.mp4">Unlocking Business Value with the Unified Management of OT and IT</A></BR>
EIOT3157BU<A HREF="NO DOWNLOAD POSTED">ExxonMobil: Lessons Learned in IoT</A></BR>
EIOT3162BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/EIOT3162BU.mp4">Living on the Edge: A Day in the Life of an IoT Device</A></BR>
EIOT3170BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/EIOT3170BU.mp4">Bring IT Security Standards to IoT and Edge with VMware and Forescout</A></BR>
EIOT3399BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/EIOT3399BU.mp4">Secure Edge Systems and IoT Devices with VMware and Intel</A></BR>
EIOT3704BUS<A HREF="NO DOWNLOAD POSTED">A New Theory of Gravity:  Shift to Edge Computing</A></BR>
MLA1294BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA1294BU.mp4">The Role of Artificial Intelligence and Machine Learning in Security</A></BR>
MLA1594BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA1594BU.mp4">Optimize Virtualized Deep Learning Performance with New Intel Architectures</A></BR>
MLA1710BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA1710BU.mp4">Managing Tomorrow's IT: Can AI and Humans Be Team Players?</A></BR>
MLA1852BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA1852BU.mp4">Next-Generation Machine Learning Architecture</A></BR>
MLA2021BU<A HREF="NO DOWNLOAD POSTED">How Machine Learning Enables the Self-Aware Hybrid Cloud</A></BR>
MLA2036BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA2036BU.mp4">VI Admin's Guide: Supporting Container-Based Machine Learning with PKS</A></BR>
MLA2336BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA2336BU.mp4">AI-Driven Support: Harnessing ML for Next-Generation Proactive Support</A></BR>
MLA2612BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA2612BU.mp4">Machine Learning with GPU Using Cloud Automation Services and Bitfusion </A></BR>
MLA2646BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA2646BU.mp4">Machine Learning Architectures: Current and Future ML Design Options</A></BR>
MLA3061BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA3061BU.mp4">Support Hub:  How Machine Learning is Making Support a Newly Magical Experience  </A></BR>
MLA3098BU<A HREF="NO DOWNLOAD POSTED">IT Superpowers: Reinforcement Learning for the Self-Driving Data Center</A></BR>
MLA3388BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA3388BU.mp4">"Scaling the Virtualization Hurdle for Machine Learning, Big Data and HPC"</A></BR>
MLA3390BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA3390BU.mp4">Running GPU-Accelerated Data Science Workflows Virtually using NVIDIA vGPU </A></BR>
MLA3411BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA3411BU.mp4">Start Your AI Journey with VMware Cloud Foundation-based Analytics Platform</A></BR>
MLA3601BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MLA3601BUS.mp4">Power the Modern Data Center: What???s New with vSphere and NVIDIA GPUs</A></BR>
OCTO1079BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO1079BU.mp4">Hybrid Cloud Runtime Reference Architecture with the VMware OCTO</A></BR>
OCTO1872BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO1872BU.mp4">Inside VMware???s Innovation Engine: Our Innovators Speak </A></BR>
OCTO1911BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO1911BU.mp4">Project Pathway - A Paradigm Shift in Corporate WAN</A></BR>
OCTO2079BU<A HREF="NO DOWNLOAD POSTED">The Age of Digital Entanglement: How Six Technologies Will Alter IT Forever</A></BR>
OCTO2501BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO2501BU.mp4">Post-Quantum Cryptography: What Every Security Professional Should Know</A></BR>
OCTO2509BU<A HREF="NO DOWNLOAD POSTED">Network Slicing and Multi-Cloud Service Orchestration for 5G</A></BR>
OCTO2527BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO2527BU.mp4">Toward a Unified Trusted Computing Framework in Virtualized Environments</A></BR>
OCTO2534BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO2534BU.mp4">An Architecture for Managing NVMe over Fabrics</A></BR>
OCTO2657BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO2657BU.mp4">VMware Blockchain: Distributed Trust at Scale</A></BR>
OCTO2718BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO2718BU.mp4">Accelerating Intra-Host PVRDMA Storage Traffic in a Future Dell AMD Server</A></BR>
OCTO2746BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO2746BU.mp4">Big Memory with VMware Cluster Memory</A></BR>
OCTO2793BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO2793BU.mp4">Employee Superpowers with Spatial Computing and Artificial Intelligence</A></BR>
OCTO2944BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/OCTO2944BU.mp4">Armed and Ready: VMware Tech and Solutions on Arm-Based Systems</A></BR>
</P>					
Hybrid Cloud (267)	<BR>				
HBI1038BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1038BU.mp4">Deploy and Maintain K8s Infrastructure with PKS on VMware Cloud Foundation</A></BR>
HBI1140BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1140BU.mp4">Power Composable Hybrid Cloud with VMware Cloud Foundation on PowerEdge MX</A></BR>
HBI1259BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1259BU.mp4">Accelerate VMware Cloud Foundation with VMware Cloud Builder</A></BR>
HBI1285BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1285BU.mp4">"Unraveling Fear, Uncertainty and Doubt in Cloud Economic Decision Risk"</A></BR>
HBI1314BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1314BU.mp4">HM Health Solutions' Journey to a Secure Healthcare Cloud</A></BR>
HBI1321BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1321BU.mp4">Building a Modern Cloud Hosting platform on VMware Cloud Foundation with VMware vCloud Director</A></BR>
HBI1338BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1338BU.mp4">BYOA and Consuming Cloud Provider Container Services</A></BR>
HBI1359BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1359BU.mp4">VMware and Runecast: Next-Gen Troubleshooting Through the vSphere Client UI</A></BR>
HBI1395BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1395BU.mp4">Hybrid Cloud State of the Union</A></BR>
HBI1400BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1400BU.mp4">Horizon on VMware Cloud Foundation: A Turnkey SDDC Solution for VDI</A></BR>
HBI1418BU<A HREF="NO DOWNLOAD POSTED">Architecting Oracle and SAP on VMware Cloud on AWS</A></BR>
HBI1420BU<A HREF="NO DOWNLOAD POSTED">Accelerating Oracle and SAP with vSphere 6.7 Hardware Accelerators</A></BR>
HBI1421BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1421BU.mp4">"Innovations in vMotion: Features, Performance, and Best Practices"</A></BR>
HBI1462BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1462BU.mp4">Planning for a Successful vSphere Upgrade</A></BR>
HBI1464BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1464BU.mp4">Upgrading your vSphere Environment: HM Health Solutions' Experience</A></BR>
HBI1488BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1488BU.mp4">Managing SSL Certificates and Vulnerability Scans in vSphere</A></BR>
HBI1494BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1494BU.mp4">Taming Multiple Distributed Private Clouds with VMware Cloud Foundation</A></BR>
HBI1502BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1502BU.mp4">Accelerate Your Hybrid Cloud Journey with VMware Cloud on AWS: What's New</A></BR>
HBI1503BU<A HREF="NO DOWNLOAD POSTED">Delivering The Easy Button for VMware Cloud</A></BR>
HBI1516BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1516BU.mp4">Building the Best of Both Worlds: A Story of Hybrid Clouds</A></BR>
HBI1517BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1517BU.mp4">Operationalizing Machine Learning Platforms with VMware Cloud Foundation</A></BR>
HBI1545BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1545BU.mp4">Microsoft Application Workloads on VMware Cloud on AWS: Doing It Right</A></BR>
HBI1546BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1546BU.mp4">How GPU-Assisted ML for Medical Research Proved to Be a Force for Good</A></BR>
HBI1576BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1576BU.mp4">A Year in the Life of an HCI Admin</A></BR>
HBI1584BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1584BU.mp4">How to Care for Your vCenter Server on Day 2</A></BR>
HBI1585BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1585BU.mp4">Manage Multiple K8 Cluster on Multiple Clouds: PKS on VMware Cloud Foundation</A></BR>
HBI1586BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1586BU.mp4">"Network Insight, Can You Quickly Help Us Migrate to VMware Cloud on AWS?"</A></BR>
HBI1592BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1592BU.mp4">Consuming NSX Edge Services: A Case Study with Rackspace</A></BR>
HBI1593BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1593BU.mp4">Easily Deploy Enterprise VDI Architecture with VMware Cloud Foundation</A></BR>
HBI1652BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1652BU.mp4">Troubleshooting VMware Cloud on AWS and NSX-T</A></BR>
HBI1688BU<A HREF="NO DOWNLOAD POSTED">Managing vSphere Certificates: A Simplified Technical Overview and Preview</A></BR>
HBI1729BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1729BU.mp4">PowerCLI Deep Dive</A></BR>
HBI1734BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1734BU.mp4">Fully Automated Template Management</A></BR>
HBI1743BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1743BU.mp4">Introduction to PowerCLI</A></BR>
HBI1855BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1855BU.mp4">Delivering Custom Services Through vCloud Director Extensibility</A></BR>
HBI1865BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1865BU.mp4">Skyline Proactive Support for the Software-Defined Data Center</A></BR>
HBI1868BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1868BU.mp4">Proactive Support with Dell SupportAssist and VMware Skyline</A></BR>
HBI1896BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1896BU.mp4">Cloud Migration and Disaster Recovery with vCloud Availability 3.0</A></BR>
HBI1900BU<A HREF="NO DOWNLOAD POSTED">Business-Critical App Validation on vSAN with VMware Cloud Foundation</A></BR>
HBI1918BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1918BU.mp4">Rackspace on Building a SDDCaaS with VMware Cloud Foundation </A></BR>
HBI1928BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1928BU.mp4">Building a Smart City with VMware Cloud Foundation and NTT Group</A></BR>
HBI1932BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1932BU.mp4">Datacenter Extension with VMware Cloud on AWS</A></BR>
HBI1947BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1947BU.mp4">Encrypting VMs on Standalone Hosts: Tech Preview</A></BR>
HBI1956BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1956BU.mp4">GSS Talks Virtual Volumes: It's Time to Step into the Future</A></BR>
HBI1964BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1964BU.mp4">Get Ahead of Support: The Keys to Understanding the Top 10 GSS Issues</A></BR>
HBI1973BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1973BU.mp4">The Next Generation of Lifecycle Management for vCenter Server </A></BR>
HBI1989BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1989BU.mp4">All About NVMe and Its Use Cases in a Cloud Environment</A></BR>
HBI2002BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2002BU.mp4">A Journey Toward a Data-Centric Future with Virtualization and RDMA </A></BR>
HBI2022BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2022BU.mp4">Case Study of a Small Business from Minnesota Building an SDDC </A></BR>
HBI2047BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2047BU.mp4">Synergy Composability for VMware Cloud Foundation</A></BR>
HBI2064BU<A HREF="NO DOWNLOAD POSTED">Building the Ultimate Hybrid Cloud with VMware Cloud Foundation and VMware Cloud on AWS</A></BR>
HBI2075BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2075BU.mp4">Demystifying Intel Optane DC Persistent Memory in a Virtualized Environment</A></BR>
HBI2090BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2090BU.mp4">Extreme Performance Series: vSphere + Intel Optane DC PMEM=Max Performance</A></BR>
HBI2109BU<A HREF="NO DOWNLOAD POSTED">Unpacking ESXi: What's New and What's Next</A></BR>
HBI2137BU<A HREF="NO DOWNLOAD POSTED">vCenter Journey from the Data Center to the Hybrid Cloud</A></BR>
HBI2138BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2138BU.mp4">Disaster Recovery with VMware HCX and VMware Site Recovery</A></BR>
HBI2146BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2146BU.mp4">Running Container-Based Workloads on VMware Cloud Foundation</A></BR>
HBI2217BU<A HREF="NO DOWNLOAD POSTED">Deep Diving in What's New with vCenter Server</A></BR>
HBI2225BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2225BU.mp4">Rapid Migration to VMware Cloud on AWS: Real-World Lessons Learned</A></BR>
HBI2227BU<A HREF="NO DOWNLOAD POSTED">A Practitioner's Guide to vCenter Server Architecture</A></BR>
HBI2247BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2247BU.mp4">Building Global Citrix Virtual Apps and Desktops with VMware Cloud on AWS</A></BR>
HBI2278BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2278BU.mp4">60 Minutes of Non-Uniform Memory Architecture</A></BR>
HBI2293BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2293BU.mp4">Build a Killer Application with VMware Cloud on Dell EMC</A></BR>
HBI2333BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2333BU.mp4">How to Get the Most Out of vSphere vMotion</A></BR>
HBI2349BU<A HREF="NO DOWNLOAD POSTED">The Business Value of Data Center Virtualization and Private Cloud</A></BR>
HBI2359BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2359BU.mp4">A Practitioner's Guide to Migrating Workloads to VMware Cloud on AWS</A></BR>
HBI2362BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2362BU.mp4">Leveraging the Latest Server Technologies in vSphere</A></BR>
HBI2367BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2367BU.mp4">Empower the Future of Modern Applications with VMware Cloud on Dell EMC</A></BR>
HBI2376BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2376BU.mp4">Deploying and Running Red Hat OpenShift on VMware</A></BR>
HBI2452BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2452BU.mp4">vCloud Director.Next : Deliver Cloud Services on Any VMware Endpoint</A></BR>
HBI2474BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2474BU.mp4">Leveraging vSphere Content Library for Template Version Management</A></BR>
HBI2494BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2494BU.mp4">Extreme Performance Series: vSphere Compute and Memory Schedulers</A></BR>
HBI2497BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2497BU.mp4">How VMware vSphere and NVIDIA GPUs Accelerate Your Organization</A></BR>
HBI2525BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2525BU.mp4">Anatomy of a Hybrid Cloud; Accelerate IT with VMware Cloud Foundation</A></BR>
HBI2526BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2526BU.mp4">Extreme Performance Series: Performance Best Practices</A></BR>
HBI2603BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2603BU.mp4">Making the Hybrid Cloud Work for You</A></BR>
HBI2642BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2642BU.mp4">Extend your Virtual Desktop infrastructure with Horizon 7 on VMware cloud. </A></BR>
HBI2721BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2721BU.mp4">"Compliance, VMware Cloud Foundation, and VMware Validated Designs"</A></BR>
HBI2726BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2726BU.mp4">Preemptive Solutions for Compliance Readiness</A></BR>
HBI2735BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2735BU.mp4">"Blueprint for a More Secure, Compliance-Ready SDDC Using Compliance Kits"</A></BR>
HBI2748BU<A HREF="NO DOWNLOAD POSTED">Driving Business Benefits Through Hybrid Cloud IT Outcomes</A></BR>
HBI2751BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2751BU.mp4">Core Storage Best Practices: Enabling Your Storage to be Reliable</A></BR>
HBI2767BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2767BU.mp4">How to Deploy the VMware Cloud Provider Platform in Your Sleep</A></BR>
HBI2792BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2792BU.mp4">Getting More Out of Site Recovery Manager: An Advanced Configuration Guide</A></BR>
HBI2797BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2797BU.mp4">Accelerate Multi Cloud adoption via VMware Managed Service Providers (MSP</A></BR>
HBI2806BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2806BU.mp4">Expedient: Hyper-growth cloud provider powered by VMware vCloud Director</A></BR>
HBI2822BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2822BU.mp4">Horizon View Cloud Pod Architecture: Best Practices and Lessons Learned</A></BR>
HBI2880BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2880BU.mp4">Extreme Performance Series: DRS 2.0 Performance Deep Dive</A></BR>
HBI2887BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2887BU.mp4">The Hitchhiker???s Guide to Hybrid Cloud on VMware Validated Design</A></BR>
HBI2915BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2915BU.mp4">Moving into Your SDDC: Migrating Workloads to VMware Cloud Foundation</A></BR>
HBI2948BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2948BU.mp4">Virtualization 101</A></BR>
HBI3051BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3051BU.mp4">Multisite vCloud Director Architecture: Best Practices and Success Stories</A></BR>
HBI3243BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3243BU.mp4">Virtualizing Mac Infrastructure at Scale: A CI Case Study with Dropbox</A></BR>
HBI3371BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3371BU.mp4">Accelerating Your On-Premises-to-Cloud Journey with Skytap on IBM Cloud</A></BR>
HBI3486BUS<A HREF="NO DOWNLOAD POSTED">Hybrid Cloud on AWS Protect all your VMware environments</A></BR>
HBI3487BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3487BUS.mp4">Rethink Data Protection & Management for VMware</A></BR>
HBI3493BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3493BUS.mp4">Best Practices for Snapshot Heavy Environments</A></BR>
HBI3496BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3496BUS.mp4">"Take IT to the track!! Self-Driving Datacenter, seatbelts required!"</A></BR>
HBI3501BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3501BUS.mp4">Cloud without Chaos: Accelerate your cloud adoption with Dell Technologies</A></BR>
HBI3502BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3502BUS.mp4">"Failproof, On-demand DR with VMware Cloud on AWS"</A></BR>
HBI3505BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3505BUS.mp4">VAIO for IT Resilience ??? Zerto & VMware with what you need to know</A></BR>
HBI3512BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3512BUS.mp4">Achieve 99.99% Uptime for Your Most Mission Critical Workloads</A></BR>
HBI3516BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3516BUS.mp4">"Scaling Virtual Infrastructure for the Enterprise: Truths, Beliefs and the Real World"</A></BR>
HBI3517BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3517BUS.mp4">Architecting an Elegant Data Management Strategy with Rubrik</A></BR>
HBI3518BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3518BUS.mp4">Modern Data Management for Service Providers with vCD and Rubrik</A></BR>
HBI3532BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3532BUS.mp4">Enhancing Data Protection for vSphere with What???s Coming from Veeam</A></BR>
HBI3533BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3533BUS.mp4">Migration and Data Strategy with VMware Cloud on AWS</A></BR>
HBI3534BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3534BUS.mp4">How to use Amazon RDS to create and manage databases on your on-premises VMware infrastructure</A></BR>
HBI3535BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3535BUS.mp4">Backups are just the start! Enhanced Data Mobility with Veeam</A></BR>
HBI3548BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3548BU.mp4">Designing VMware Cloud on AWS with cloud based NFS datastores</A></BR>
HBI3549BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3549BUS.mp4">Accelerate Innovation by taking advantage of hybrid multicloud environments</A></BR>
HBI3569BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3569BUS.mp4">Data Protection in the Hybrid Cloud: Comprehensive??? and Simple</A></BR>
HBI3591BUS<A HREF="NO DOWNLOAD POSTED">Building Modern Hybrid Applications with Google Cloud Anthos and VMware</A></BR>
HBI3594BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3594BUS.mp4">Leap Forward and Defy Limits with HPE Primera and Nimble dHCI for VMware</A></BR>
HBI3604BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3604BUS.mp4">AWS 101: Cloud is the new normal</A></BR>
HBI4115BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI4115BU.mp4">Running High Value Workloads on the Dell Technologies Cloud with VCF Integration and Dell EMC Storage</A></BR>
HBI4198BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI4198BUS.mp4">Any Workload Anywhere Enabling Hybrid Cloud from Data Center to the Edge</A></BR>
HBI4250BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI4250BUS.mp4">How to Extend Availability to the Application Layer Across the Hybrid Cloud </A></BR>
HBI4355BU<A HREF="NO DOWNLOAD POSTED">Power the Future of Hybrid IT with VMware Cloud Services  </A></BR>
HBI4500BU<A HREF="NO DOWNLOAD POSTED">Project Pacific Technical Overview: Unifying vSphere and Kubernetes</A></BR>
HBI4937BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI4937BU.mp4">Introducing Project Pacific: Transforming vSphere into the App Platform of the Future</A></BR>
HBI4988BUS<A HREF="NO DOWNLOAD POSTED">True Stories: Innovation powered by VMware Cloud Foundation</A></BR>
HBI5577BES<A HREF="NO DOWNLOAD POSTED">Be Datacenter ready for Hybrid Multi Cloud with NetApp HCI & VMware vSphere</A></BR>
HBO1080BU<A HREF="NO DOWNLOAD POSTED">Continuous Application Delivery with Code Stream: A customer journey</A></BR>
HBO1094BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1094BU.mp4">Best Practices for vRealize Operations Workload Optimization</A></BR>
HBO1136BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1136BU.mp4">It's Not 2005 Anymore: Stop Using Excel for Capacity Management</A></BR>
HBO1180BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1180BU.mp4">The Big Ticket: What???s New in vRealize Operations</A></BR>
HBO1183BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1183BU.mp4">Introducing vRealize Operations as a Service</A></BR>
HBO1288BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1288BU.mp4">Accelerate application deployment with vRealize Automation Cloud: A Customer Journey </A></BR>
HBO1323BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1323BU.mp4">Evolving vRealize Automation</A></BR>
HBO1422BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1422BU.mp4">How vRealize Suite Works with VMware Cloud on AWS</A></BR>
HBO1649BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1649BU.mp4">Creating a Cohesive Monitoring Strategy with IHS Markit</A></BR>
HBO1689BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1689BU.mp4">Get More Insight into Your Network with vRealize Network Insight</A></BR>
HBO1755BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1755BU.mp4">"Tales from the field, vSAN production Operations for real customer success "</A></BR>
HBO1786BU<A HREF="NO DOWNLOAD POSTED">The Secrets to Achieving a Competitive Advantage with vRealize Automation</A></BR>
HBO1899BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1899BU.mp4">Network Automation with NSX and VMware Cloud Automation</A></BR>
HBO2114BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO2114BU.mp4">Architecting and Extending vRealize Operations for VMware Cloud on AWS</A></BR>
HBO2281BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO2281BU.mp4">Getting Started with Site Recovery Manager</A></BR>
HBO2643BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO2643BU.mp4">The Story of VMware Multi-Cloud</A></BR>
HBO2768BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO2768BU.mp4">Site Recovery Manager Technical Walk-Through with Engineering</A></BR>
HBO2769BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO2769BU.mp4">Kubernetes and Cloud Automation Services: A Primer</A></BR>
HBO2789BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO2789BU.mp4">Drive Accountability and Efficiency with VMware???s Cloud Management Platform</A></BR>
HBO2958BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO2958BU.mp4">Site Recovery Manager: DR Testing at Its Finest</A></BR>
HBO2979BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO2979BU.mp4">How American Airlines Built a More Secure Hybrid Cloud with IBM and VMware HCX</A></BR>
HBO3088BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO3088BU.mp4">"Game of Clouds E1: The Map, the Law and the Future of VMware Cloud Management"</A></BR>
HBO3090BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO3090BU.mp4">Game of Clouds E3: The Magic and the Reality of Self Driving Operations</A></BR>
HBO3093BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO3093BU.mp4">Game of Clouds E2: Winning the Battle of IT Automation and Self-Service</A></BR>
HBO3381BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO3381BU.mp4">Applying Machine Learning to Reduce Day 2 Troubleshooting and Headaches??</A></BR>
HBO3561BU<A HREF="NO DOWNLOAD POSTED">Leveraging advanced features of vRealize Operations in security policies</A></BR>
HBO3626BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO3626BUS.mp4">Azure VMware Solutions ??? Run your VMware workloads natively on Azure</A></BR>
HBO3784BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO3784BUS.mp4">Milliseconds Matter - Global Connectivity in the Hybrid Cloud  Era</A></BR>
HBO4249BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO4249BUS.mp4">How to Obtain and Use analytics to Optimize Hybrid-cloud Deployments</A></BR>
HCI1041BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1041BU.mp4">Show Me the Money: Measuring ROI with HCI</A></BR>
HCI1048BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1048BU.mp4">Real-World vSAN Deployment Considerations</A></BR>
HCI1086BU<A HREF="NO DOWNLOAD POSTED">Modernizing the Data Center: Faster to Market Through Innovation for Sky</A></BR>
HCI1192BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1192BU.mp4">Understand vSAN in Less Than 1 Hour</A></BR>
HCI1207BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1207BU.mp4">HCI Management: Current and Future</A></BR>
HCI1210BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1210BU.mp4">Current and Future of vSAN Operations with vRealize Operations</A></BR>
HCI1231BU<A HREF="NO DOWNLOAD POSTED">High Storage Capacity Deployments on VMware Cloud Leveraging Elastic vSAN</A></BR>
HCI1308BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1308BU.mp4">Come Dive In: An In-Depth Look at Day 2 Operations with VMware vSAN </A></BR>
HCI1342BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1342BU.mp4">Deconstructing vSAN: A Deep Dive into the Internals of vSAN</A></BR>
HCI1346BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1346BU.mp4">A Practical Guide to Troubleshooting vSAN Performance</A></BR>
HCI1417BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1417BU.mp4">HCI Tools: Assessing and Sizing a Real Customer Environment for vSAN</A></BR>
HCI1606BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1606BU.mp4">SAP HANA on vSAN: Best Practice Recommendations and Lessons Learned</A></BR>
HCI1607BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1607BU.mp4">Architecting Next-Gen Applications: Cassandra on vSAN in a Hybrid Cloud</A></BR>
HCI1619BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1619BU.mp4">Troubleshooting Performance Issues with vSAN Performance Diagnostics</A></BR>
HCI1620BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1620BU.mp4">Artificial Intelligence and Machine Learning for HCI:  Where We???re Going</A></BR>
HCI1650BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1650BU.mp4">Optimize vSAN performance using vRealize Operations and Reinforcement Learning</A></BR>
HCI1678BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1678BU.mp4">"Operationalizing VMware vSAN: You???ve Implemented vSAN, Now What?"</A></BR>
HCI1701BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1701BU.mp4">Leveraging vSAN as a Path to the Hybrid Cloud World</A></BR>
HCI1712BU<A HREF="NO DOWNLOAD POSTED">The vSAN Hardware Platform and Its Importance on vSAN Deployment</A></BR>
HCI1724BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1724BU.mp4">"Back with Act 2.0: SDDC, Automation, Apps, and Beyond"</A></BR>
HCI1757BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1757BU.mp4">Optimizing vSAN for Performance </A></BR>
HCI1821BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1821BU.mp4">Designing and Managing a vSAN Cluster for the Highest Availability Levels</A></BR>
HCI1825BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1825BU.mp4">Automate VMware HCI Deployments at Any Scale with PowerCLI</A></BR>
HCI1833BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1833BU.mp4">Successfully Architect VMware HCI for Remote and Branch Offices</A></BR>
HCI1845BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1845BU.mp4">Top 10 Things to Know About vSphere and vSAN Networking</A></BR>
HCI1864BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1864BU.mp4">"Automating vSAN from CLI to API: PowerCLI, Govc, and Beyond"</A></BR>
HCI1878BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1878BU.mp4">Successful Deployment of Splunk on VMware HCI: VMware IT Case Study</A></BR>
HCI1891BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1891BU.mp4">Best Practices for HCI Performance Benchmarking</A></BR>
HCI1941BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1941BU.mp4">Architecting Hadoop Workloads on HCI Powered by VMware vSAN</A></BR>
HCI1952BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1952BU.mp4">Resync Redefined: Safety Efficiency and Monitoring of vSAN Resync</A></BR>
HCI1981BU<A HREF="NO DOWNLOAD POSTED">Modernize Your HCI Data Center with vRealize Operations and vSAN</A></BR>
HCI2040BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2040BU.mp4">The Definitive Guide to vSphere Storage for Kubernetes </A></BR>
HCI2055BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2055BU.mp4">Data Protection Solutions for VMware vSAN</A></BR>
HCI2097BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2097BU.mp4"> Top 5 Reasons to Move to HCI</A></BR>
HCI2185BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2185BU.mp4">A Guide to vSAN Performance: A VM-Centric Approach</A></BR>
HCI2256BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2256BU.mp4">HCI Upgrade: Let's Simplify and Automate the Mundane</A></BR>
HCI2344BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2344BU.mp4">Achieving Enterprise Comfort with vSAN </A></BR>
HCI2733BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2733BU.mp4">Hyperconverged Infrastructure: Present and Future</A></BR>
HCI2763BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2763BU.mp4">Technical Deep Dive on Cloud Native Storage for vSphere</A></BR>
HCI2888BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2888BU.mp4">Site Recovery Manager 8.2: What's New and Demo</A></BR>
HCI2894BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2894BU.mp4">Tech Preview of Site Recovery Manager with Virtual Volumes</A></BR>
HCI3062BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI3062BU.mp4">Healthcare on vSAN</A></BR>
HCI3120BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI3120BU.mp4">Architecting for Operational Excellence in Higher Education</A></BR>
HCI3321BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI3321BU.mp4">The HPE Software-Defined Data and Analytics Platform with VMware</A></BR>
HCI3476BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI3476BUS.mp4">How to match workloads to clouds for best fit consumption and management.</A></BR>
HCI3482BUS<A HREF="NO DOWNLOAD POSTED">Build an Agile Hybrid Cloud with VMware and HPE Composable Solutions</A></BR>
HCI3560BU<A HREF="NO DOWNLOAD POSTED">A New Model for IAAS: Shifting SLAs to VMware with VMC on Dell EMC</A></BR>
HCI3710BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI3710BUS.mp4">Optimize Infrastructure Modernization using vSAN and Intel Optane Technologies</A></BR>
HBI1027BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1027BU.mp4">VMware Cloud Foundation on VxRail: Accelerate Your Path to Hybrid Cloud</A></BR>
HBI1145BU<A HREF="NO DOWNLOAD POSTED">VMware HCX for Cloud Providers Architecture Deep Dive</A></BR>
HBI1158BU<A HREF="NO DOWNLOAD POSTED">vRealize Operations for Cloud Providers</A></BR>
HBI1223BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1223BU.mp4">VMware Cloud on AWS: Networking and Security Design</A></BR>
HBI1229BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1229BU.mp4">Zero to DR in 60 Minutes: VMware Site Recovery DRaaS Technical Deep Dive</A></BR>
HBI1286BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1286BU.mp4">VMware Cloud Foundation on VxRail: The Simplest Path to Hybrid Cloud</A></BR>
HBI1325BU<A HREF="NO DOWNLOAD POSTED">VMware Cloud on AWS and vRealize Automation Cloud ??? Better Together</A></BR>
HBI1396BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1396BU.mp4">VMware Cloud Services Architecture</A></BR>
HBI1402BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1402BU.mp4">VMware Cloud on AWS: Deploying a SaaS Platform Globally</A></BR>
HBI1414BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1414BU.mp4">VMware Cloud on AWS SDDC Lifecycle Management and Customer Experience</A></BR>
HBI1428BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1428BU.mp4">VMware Cloud on Dell EMC: Technical Overview</A></BR>
HBI1432BUR<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1432BUR.mp4">"VMware Cloud Foundation: Strategy, Capabilities, and Technology Direction"</A></BR>
HBI1448BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1448BU.mp4">VMware Cloud Foundation and vRealize Suite: Better Together</A></BR>
HBI1463BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1463BU.mp4">VMware Cloud on AWS: Advanced Automation Techniques</A></BR>
HBI1469BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1469BU.mp4">vSphere Client Journey from a Customer's Perspective</A></BR>
HBI1514BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1514BU.mp4">VMware Cloud Foundation and HPE Synergy: The Ultimate Hybrid Cloud</A></BR>
HBI1539BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1539BU.mp4">What's New in vSphere Health?</A></BR>
HBI1540BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1540BU.mp4">VMware Tools: The Lowdown</A></BR>
HBI1637BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1637BU.mp4">VMware Validated Design: Intro and Its Future with VMware Cloud Foundation</A></BR>
HBI1643BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1643BU.mp4">VMware Cloud Marketplace: Buy ISV Apps for VMware Platforms</A></BR>
HBI1764BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1764BU.mp4">vSphere Admin Guide to VMware Validated Designs and VMware Cloud Foundation</A></BR>
HBI1866BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1866BU.mp4">VMware Cloud on AWS Storage Architecture and Design Options</A></BR>
HBI1871BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1871BU.mp4">VMware Cloud on AWS: Developing Hybrid Applications with AWS Services</A></BR>
HBI1924BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1924BU.mp4">VMware Cloud on AWS: SDDC Availability Deep Dive</A></BR>
HBI1953BU<A HREF="NO DOWNLOAD POSTED">vSphere Security: News You Can Use</A></BR>
HBI1967BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1967BU.mp4">Workload Migration Techniques for On-Premises and Cloud Infrastructures</A></BR>
HBI1975BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1975BU.mp4">VMware Cloud on Dell EMC: Technical Deep Dive</A></BR>
HBI1980BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI1980BU.mp4">"VMware Cloud on Dell EMC: Customer Experiences, Architectures, and Benefits"</A></BR>
HBI2044BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2044BU.mp4">VMware Cloud Foundation Deep Dive</A></BR>
HBI2136BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2136BU.mp4">vSphere Networking in the Data-Centric Future</A></BR>
HBI2186BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2186BU.mp4">vSphere HA and DRS Hybrid Cloud Deep Dive</A></BR>
HBI2267BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2267BU.mp4">vSAN Stretched Clusters and DR Simplified by VMware Cloud Foundation</A></BR>
HBI2559BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2559BU.mp4">VMware Cloud Foundation: Real-World Deployment Experiences</A></BR>
HBI2641BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2641BU.mp4">What Is a VMware Cloud Provider?</A></BR>
HBI2654BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2654BU.mp4">What's New in VMware Fusion and VMware Workstation</A></BR>
HBI2853BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2853BU.mp4">vSphere Virtual Volumes: Technical Deep Dive</A></BR>
HBI2893BUR<A HREF="NO DOWNLOAD POSTED">What's New with vSphere?</A></BR>
HBI2961BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI2961BU.mp4">vSphere Remote Office Branch Office: Benefits of Virtualized Remote Offices</A></BR>
HBI3049BU<A HREF="NO DOWNLOAD POSTED">VMware Cloud on AWS Outposts: Understanding the Tech and Business Value</A></BR>
HBI3109BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3109BU.mp4">VMware Site Recovery: What???s New with DRaaS on VMware Cloud on AWS </A></BR>
HBI3295BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3295BU.mp4">VMware Cloud on AWS Compliance and Privacy Strategy</A></BR>
HBI3306BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3306BU.mp4">VMware Cloud on AWS SRE Day 2 Operations: Service Support </A></BR>
HBI3416BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI3416BUS.mp4">Why should I use Virtual Volumes? A technical review.</A></BR>
HBI4446BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBI4446BU.mp4">VMware in Any Cloud: Introducing Microsoft Azure and Google Cloud VMware Solutions</A></BR>
HBO1138BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1138BU.mp4">"Yes, Mr. CFO, IT Is Expensive ??? Understand Why with vRealize Operations"</A></BR>
HBO1139BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HBO1139BU.mp4">You Get a Cloud and You Get a Cloud: Monitoring with vRealize Operations</A></BR>
HBO2498BU<A HREF="NO DOWNLOAD POSTED">vRealize Automation Cloud with VMware Cloud on AWS: IHS Markit </A></BR>
HBO3559BU<A HREF="NO DOWNLOAD POSTED">"vRealize Automation Cloud: Developers??? Paradise on any cloud, on any device"</A></BR>
HCI1175BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1175BU.mp4">vSAN Technical Deep Dive</A></BR>
HCI1177BU<A HREF="NO DOWNLOAD POSTED">vSAN Stretched Clusters Technical Deep Dive</A></BR>
HCI1199BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1199BU.mp4">vSAN Data-at-Rest Encryption Deep Dive</A></BR>
HCI1215BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1215BU.mp4">vSAN: End-to-End Demos of the Latest vSAN Operational Enhancements </A></BR>
HCI1293BU<A HREF="NO DOWNLOAD POSTED">vSAN Resilience: What's New to Help Run Your Workloads With Confidence</A></BR>
HCI1330BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1330BU.mp4">What's New in VMware vSAN 6.7 Update 3</A></BR>
HCI1339BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1339BU.mp4">vSAN Administration Optimized Through vRealize Operations and Log Insight</A></BR>
HCI1754BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1754BU.mp4">VMware Data Management: 4 Core Use Cases Every Company Must Address</A></BR>
HCI1836BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1836BU.mp4">vSAN Networking Design and Configuration Decisions</A></BR>
HCI1870BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI1870BU.mp4">vSphere High Availability: Recommended Practices for VMware vSAN</A></BR>
HCI2046BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2046BU.mp4">vSAN at U-Haul: Moving From a Painful Start to Massive Success</A></BR>
HCI2049BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2049BU.mp4">vSAN Trends from the Trenches: What Our Largest Global Customers Are Doing</A></BR>
HCI2168BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2168BU.mp4">vSAN Stretched Cluster: Considerations and Best Practices</A></BR>
HCI2380BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2380BU.mp4">vSAN First Aid and Emergency Response Guide</A></BR>
HCI2547BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2547BU.mp4">VMware vSAN for Cloud Providers: Technical Overview</A></BR>
HCI2978BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI2978BU.mp4">vSAN 2-Node in ROBO Locations: Lessons from the Field</A></BR>
HCI3450BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI3450BU.mp4">vSAN Best Practices</A></BR>
HCI3451BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/HCI3451BU.mp4">vSphere External Storage for the Hybrid Cloud</A></BR>
MCO2457BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO2457BU.mp4">vRealize Suite Lifecycle Manager - Technical Deep Dive and Troubleshooting</A></BR>
</P>					
Modern Apps (57)	<BR>				
BCA1116BU<A HREF="NO DOWNLOAD POSTED		Architecting Business-Critical Oracle Workloads on the VMware SDDC Platform</A></BR>
BCA1117BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1117BU.mp4">A Journey of Oracle Workloads from On-Premises to VMware Cloud on AWS</A></BR>
BCA1181BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1181BU.mp4">Monitor All the Things: Application Monitoring with vRealize Operations</A></BR>
BCA1257BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1257BU.mp4">Keys to Successful SQL Server Availability Deployments with vSphere</A></BR>
BCA1292BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1292BU.mp4">Multi-Cloud Application Platforms for Infrastructure Engineers</A></BR>
BCA1332BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1332BU.mp4">The Different Forms of Machine Learning: How They Fit with VMware</A></BR>
BCA1393BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1393BU.mp4">SAP HANA on vSphere 6.7u2 and 2nd Generation Intel?? Xeon?? Scalable Processor Best Practices</A></BR>
BCA1430BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1430BU.mp4">Accelerating Application/Database Performance in the Self-Learning SDDC</A></BR>
BCA1482BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1482BU.mp4">"Extreme Performance Series: SQL Server, Oracle, and SAP Monster DB VMs"</A></BR>
BCA1542BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1542BU.mp4">SQL Server Workloads on VMware vSphere: Configuration Recommendations</A></BR>
BCA1563BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1563BU.mp4">High-Performance Virtualized Spark Clusters on Kubernetes for Deep Learning</A></BR>
BCA1668BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1668BU.mp4">My Application Is Timing Out. Don???t Blame the Oracle DBA. </A></BR>
BCA1697BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1697BU.mp4">Virtualize Your Organization's Research and Science Workloads: How and Why</A></BR>
BCA1901BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA1901BU.mp4">SGX Secure Enclaves: The Future of Application Security in the Cloud</A></BR>
BCA2058BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2058BU.mp4">VMware SDDC: An Ideal Platform for Running High-Performance Computing</A></BR>
BCA2082BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2082BU.mp4">Virtualize Active Directory the Right Way</A></BR>
BCA2087BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2087BU.mp4">How to Optimize the VMware Support Experience</A></BR>
BCA2149BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2149BU.mp4">VM Performance Demystified and Best Practices to Optimize</A></BR>
BCA2290BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2290BU.mp4">"Heard about Mars v. Oracle? Explore Oracle Audits with Experts, Attorneys"</A></BR>
BCA2533BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2533BU.mp4">Licensing Oracle and SQL Server on vSphere</A></BR>
BCA2551BU<A HREF="NO DOWNLOAD POSTED">Extreme Performance Series: Low Latency Media and Entertainment Workloads</A></BR>
BCA2626BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2626BU.mp4">Elastic AI Infrastructure on vSphere: Virtual GPU and FPGA with Bitfusion</A></BR>
BCA2630BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2630BU.mp4">Migrate Oracle Unix to Virtual Linux: LicenseFortress Assures Compliance</A></BR>
BCA2737BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2737BU.mp4">Running SAP Workloads on VMware Cloud on AWS</A></BR>
BCA2740BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2740BU.mp4">"SAP HANA on vSphere, vSAN, VMware Cloud: Roadmap and Certification Strategy"</A></BR>
BCA2780BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2780BU.mp4">"Running with Zero Downtime, Zero Data Loss: vSphere Fault Tolerance"</A></BR>
BCA2800BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2800BU.mp4">Automating Cloud Solutions for SAP</A></BR>
BCA2861BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA2861BU.mp4">Supporting SQL Server Failover Cluster Instances Without Those Pesky RDMs???</A></BR>
BCA3199BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/BCA3199BU.mp4">Scottish Government Virtualizes Critical Legacy Apps in VMware Cloud on AWS</A></BR>
BCA3382BU<A HREF="NO DOWNLOAD POSTED">Move SAP Workloads on VMware into Cloud without Re-architecting</A></BR>
BCA4906BUS<A HREF="NO DOWNLOAD POSTED">Mission Critical as Code Goes Public</A></BR>
KUB1126BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1126BU.mp4">Cloud Native Fundamentals: Containers and Kubernetes 101 for the VI Admin</A></BR>
KUB1133BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1133BU.mp4">Peanut Butter and Jelly: Why Virtual Machines and Containers Go Together</A></BR>
KUB1168BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1168BU.mp4">Monitor Health State of a Large Fleet of Kubernetes Clusters with Wavefront</A></BR>
KUB1208BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1208BU.mp4">Deep Dive - Kubernetes Resource Management for vSphere Admins</A></BR>
KUB1218BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1218BU.mp4">Kubernetes Security: Move Fast Without Breaking Things</A></BR>
KUB1357BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1357BU.mp4">Full-Stack Troubleshooting: Wavefront Automated K8s and App Observability</A></BR>
KUB1762BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1762BU.mp4">The vSphere Administrator's Guide to the Kubernetes Galaxy</A></BR>
KUB1835BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1835BU.mp4">Introducing VMware Tanzu Mission Control: Manage Kubernetes at Scale</A></BR>
KUB1840BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1840BU.mp4">Run Upstream Kubernetes Consistently Across Clouds with VMware Tanzu</A></BR>
KUB1851BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1851BU.mp4">"More Devs, No Problem: Managing Self-service Access with VMware Tanzu "</A></BR>
KUB1862BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1862BU.mp4">"Service Mesh, Tracing, Prometheus: Wavefront Provides Observability for All"</A></BR>
KUB1879BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1879BU.mp4">Guts and Glory: How to Make Kubernetes Work for Your Organization</A></BR>
KUB1939BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1939BU.mp4">Cross-Cluster and Cross-Cloud Service Mesh Architecture and Use Cases</A></BR>
KUB1995BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB1995BU.mp4">Design and Deploy Windows Containers on Kubernetes with VMware PKS</A></BR>
KUB2011BU<A HREF="NO DOWNLOAD POSTED">Case Study: How Domino's Delivers Pizzas with Containers and Kubernetes</A></BR>
KUB2069BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB2069BU.mp4">Extend Your Existing vSphere Environments to Operate Kubernetes</A></BR>
KUB2410BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB2410BU.mp4">Pivotal Cloud Foundry Cross-Stack Visibility with Wavefront</A></BR>
KUB2517BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB2517BU.mp4">Kubernetes Lessons Learned: Tips and Tricks from 50+ Kubernetes Deployments</A></BR>
KUB2663BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB2663BU.mp4">Unifying IT Monitoring with vSAN Telegraf Plugin for Wavefront</A></BR>
KUB2857BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB2857BU.mp4">Case Study: How Swisscom Simplified Multitenancy with Kubernetes</A></BR>
KUB2883BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB2883BU.mp4">Transform Your vSphere Team to Operate Kubernetes as a Service</A></BR>
KUB3002BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB3002BU.mp4">Run Kubernetes run. Five steps to run VMware PKS day-to-day</A></BR>
KUB3415BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB3415BUS.mp4">"Kubernetes in the Enterprise? PKS, Pure Storage, and the VMware SDDC"</A></BR>
KUB3507BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB3507BUS.mp4">Running Enterprise Grade Kubernetes on vSAN: Google Anthos and VMware Enterprise PKS</A></BR>
KUB4114BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB4114BU.mp4">Enterprise-ready Kubernetes: Your Path to Cloud-native Applications with Dell Technologies</A></BR>
KUB4298BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/KUB4298BUS.mp4">"You???ve made Kubernetes available to your Developers, Now What?"</A></BR>
</P>					
Multi-Cloud (27)	<BR>				
MCO1169BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1169BU.mp4">Manage Cost in Hundreds of Kubernetes Clusters in a Multi-Cloud Environment</A></BR>
MCO1186BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1186BU.mp4">"Wavefront, We Have a Problem: Quicker Fault Isolation Across the Stack"</A></BR>
MCO1213BU<A HREF="NO DOWNLOAD POSTED">Migrate Your Business to the Cloud and Keep Your Expenses on the Ground</A></BR>
MCO1348BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1348BU.mp4">Customer Use Case: Cloud Transformation with Wavefront by VMware</A></BR>
MCO1405BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1405BU.mp4">Observability 101 for Practitioners: Maximizing Cloud Services Reliability</A></BR>
MCO1425BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1425BU.mp4">Deep Dive: Use VMware Secure State to Secure Your Multi-Cloud Environments</A></BR>
MCO1427BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1427BU.mp4">How Real Customers Fixed Risky Misconfigurations in AWS and Azure</A></BR>
MCO1528BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1528BU.mp4">Totally Bankable: Making Multi-Cloud Management a (Cost-Effective) Reality</A></BR>
MCO1626BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1626BU.mp4">AWS Security Breach? How to Prevent and Recover From It</A></BR>
MCO1642BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1642BU.mp4">8x8 Shares its Operational Practices for Cloud Service SLOs and SLAs</A></BR>
MCO1687BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1687BU.mp4">Is IT Ready to Enable Success in Your Multi-Cloud Environment?</A></BR>
MCO1781BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO1781BU.mp4">Application Migration in Multi-Cloud Using Network Insight and CloudHealth</A></BR>
MCO2050BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO2050BU.mp4">Multi-Cloud Pattern: The Six Sevens of Data Orchestration</A></BR>
MCO2231BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO2231BU.mp4">What You Need to Know About the VMware Cloud Assembly IaaS API</A></BR>
MCO2414BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO2414BU.mp4">Developing Your Cloud Center of Excellence with CloudHealth</A></BR>
MCO2417BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO2417BU.mp4">Master Reserved Instance Management with CloudHealth</A></BR>
MCO2418BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO2418BU.mp4">Optimizing Public Cloud Spend with CloudHealth and Onica</A></BR>
MCO2435BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO2435BU.mp4">Keep Track of Your Costs; It's Imperative and Good for Your Health</A></BR>
MCO2438BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO2438BU.mp4">Not Your Grandfather???s CMP: CloudHealth Modernize Cloud Management</A></BR>
MCO2439BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO2439BU.mp4">Introduction to Multi-Cloud Governance</A></BR>
MCO2823BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO2823BU.mp4">Avengers Style - How BookMyShow Optimizes Cloud Apps with Wavefront?</A></BR>
MCO2970BU<A HREF="NO DOWNLOAD POSTED">Building Compute Towers: Intent-Based Provisioning in a Multi-Cloud World</A></BR>
MCO3148BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO3148BU.mp4">"Bridging IT and OT by combining Pulse IoT Center, vRA and vRO"</A></BR>
MCO3529BU<A HREF="NO DOWNLOAD POSTED">The Multi-cloud Builder's Journey </A></BR>
MCO3531BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO3531BU.mp4">Securing your Software Supply Chain in a Multi-cloud World </A></BR>
MCO3538BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO3538BUS.mp4">Best Practices for Cloud Migration and Acceleration </A></BR>
MCO4151BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/MCO4151BUS.mp4">???In Defense of the Multi-Cloud</A></BR>
</P>		">	
Network & Security (91)	<BR>	">	
CNET1028BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1028BU.mp4">Demystifying the NSX-T Control and Data Plane</A></BR>
CNET1033BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1033BU.mp4">Introduction to NSX Service Mesh</A></BR>
CNET1069BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1069BU.mp4">NSX-T Deep Dive: Layer 3 Routing</A></BR>
CNET1072BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1072BU.mp4">NSX-T Design for Small to Mid-Sized Data Centers</A></BR>
CNET1100BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1100BU.mp4">"NSX-T for Service Providers: Functionality, Technology, Use Cases"</A></BR>
CNET1219BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1219BU.mp4">VMware Cloud on AWS: NSX-T Networking and Security Deep Dive</A></BR>
CNET1243BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1243BU.mp4">NSX-T Deep Dive: Performance</A></BR>
CNET1244BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1244BU.mp4">NSX-T Design for Pivotal Application Service (PAS</A></BR>
CNET1251BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1251BU.mp4">"NSX-T Install, Upgrade and Day 2 Operations"</A></BR>
CNET1270BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1270BU.mp4">NSX-T Deep Dive: Kubernetes Networking</A></BR>
CNET1296BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1296BU.mp4">The Future of Networking with NSX</A></BR>
CNET1334BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1334BU.mp4">NSX-T Design for Multi-Site Networking and Disaster Recovery</A></BR>
CNET1356BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1356BU.mp4">NSX-T Deep Dive: Load Balancing</A></BR>
CNET1365BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1365BU.mp4">NSX Cloud Deployment and Architecture Deep Dive </A></BR>
CNET1444BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1444BU.mp4">Lessons Learned: Deploying OpenShift with VMware SDDC</A></BR>
CNET1474BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1474BU.mp4">NSX and Cisco ACI: Running Your SDDC on a Cisco Underlay</A></BR>
CNET1498BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1498BU.mp4">Transitioning from NSX for vSphere to NSX-T</A></BR>
CNET1511BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1511BU.mp4">NSX-T Deep Dive: Logical Switching</A></BR>
CNET1575BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1575BU.mp4">Introduction to VMware NSX</A></BR>
CNET1579BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1579BU.mp4">Digital Transformation with NSX SDDC: Quantifying ROI with Data</A></BR>
CNET1582BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1582BU.mp4">"Extend Your Network and Security to AWS, Azure, and IBM Cloud"</A></BR>
CNET1600BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1600BU.mp4">NSX Cloud: Consistently Extend NSX to AWS and Azure</A></BR>
CNET1692BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1692BU.mp4"> What's New with vRealize Network Insight (vRNI</A></BR>
CNET1908BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1908BU.mp4">NSX-T Design for VMware Validated Designs and VMware Cloud Foundation</A></BR>
CNET1909BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1909BU.mp4">NSX-T Deep Dive: Policy API </A></BR>
CNET1960BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET1960BU.mp4">Network Insight: Optimize and troubleshoot apps across NSX DC and SD-WAN</A></BR>
CNET2061BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2061BU.mp4">Next-Generation Reference Design with NSX-T: Part 1</A></BR>
CNET2067BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2067BU.mp4">"VMware Cloud with NSX on AWS, Dell EMC, and AWS Outposts"</A></BR>
CNET2068BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2068BU.mp4">"Next Generation Reference Design with NSX-T, Part 2"</A></BR>
CNET2141BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2141BU.mp4">HCX - Automating Workload Migration for Data Centers and Clouds</A></BR>
CNET2406BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2406BU.mp4">NSX-T Design and Operations for PKS </A></BR>
CNET2503BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2503BU.mp4">Overview of Network Automation with NSX-T</A></BR>
CNET2520BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2520BU.mp4">Hybrid Cloud and Multi-Cloud Networking with NSX</A></BR>
CNET2588BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2588BU.mp4">Network Automation with NSX-T and vRealize Automation</A></BR>
CNET2604BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2604BU.mp4">Introduction to Container Networking</A></BR>
CNET2648BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2648BU.mp4">NSX-T Deep Dive: Automation from Install to Operations</A></BR>
CNET2650BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2650BU.mp4">Virtual Networking Across Data Centers and Clouds with NSX </A></BR>
CNET2758BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2758BU.mp4">A Walk-Through of the New NSX-T GUI</A></BR>
CNET2841BU<A HREF="NO DOWNLOAD POSTED">NSX-T Deep Dive: Connecting Clouds and Data Centers via NSX-T VPN</A></BR>
CNET2868BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET2868BU.mp4">Why the Rise of DevOps and DevSecOps Mandate Network Virtualization</A></BR>
CNET3048BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET3048BU.mp4">NSX-T Operations and Troubleshooting</A></BR>
CNET3380BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET3380BU.mp4">Using NSX-T to Modernize Your IT Infrastructure by IBM</A></BR>
CNET3628BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET3628BUS.mp4">"Edge to Hybrid Cloud, the Network Matters"</A></BR>
CNET3671BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET3671BU.mp4">Modern Load Balancing 101</A></BR>
CNET3672BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET3672BU.mp4">Deep Automation and Self-service for Application Delivery</A></BR>
CNET3674BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET3674BU.mp4">Consistent Load Balancing for Multi-Cloud Environments</A></BR>
CNET4116BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET4116BU.mp4">The future of SD-WAN and SDN ??? Co-engineered by Dell EMC & VMware</A></BR>
CNET5669BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET5669BUS.mp4">NETSCOUT ASI for Visibility & Troubleshooting into Applications with NSX-T</A></BR>
CNET5670BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/CNET5670BUS.mp4">Application Visibility & Troubleshooting the Virtual Cloud Network and NSX</A></BR>
NEDG1085BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG1085BU.mp4">Breaking with Tradition: How VMware IT Transformed WAN with VMware SD-WAN</A></BR>
NEDG1333BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG1333BU.mp4">Consuming Service Provider SD-WAN Services</A></BR>
NEDG2576BU<A HREF="NO DOWNLOAD POSTED">"Know, Understand, Execute: Network Monitoring and Analytics with SD-WAN"</A></BR>
NEDG2577BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2577BU.mp4">Why Your Digital Transformation Needs SD-WAN</A></BR>
NEDG2579BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2579BU.mp4">"SD-WAN Use Cases: Hybrid WAN, Cloud Shift, Security, and More"</A></BR>
NEDG2592BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2592BU.mp4">"All the Acronyms: uCPE, NFV, and SD-WAN for the Future and Beyond"</A></BR>
NEDG2596BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2596BU.mp4">SD-WAN and 5G: A Two-Pronged Approach to a Strategic Network Edge </A></BR>
NEDG2598BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2598BU.mp4">SD-WAN and Your Business: Ensuring You Have a Business-Ready Network</A></BR>
NEDG2600BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2600BU.mp4">Achieving a Best-of-Breed SD-WAN Technology Ecosystem</A></BR>
NEDG2601BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2601BU.mp4">Going All the Way with SD-WAN and Virtualization: A Case Study</A></BR>
NEDG2605BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2605BU.mp4">"Network Edge: The New Frontier for EUC, IoT, 5G, and Beyond"</A></BR>
NEDG2608BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2608BU.mp4">Easy Peasy: Answers for Your Common SD-WAN Adoption Questions</A></BR>
NEDG2613BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2613BU.mp4">Extending vRealize Network Insight Capabilities with VMware SD-WAN</A></BR>
NEDG2617BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG2617BU.mp4">"Match Made in Heaven: SD-WAN for Azure, AWS, and Google Cloud Platform "</A></BR>
NEDG3480BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/NEDG3480BU.mp4">Dell IT: Our Software-Defined Journey - Implementing VMware SD-WAN by VeloCloud</A></BR>
SAI1017BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI1017BU.mp4">"Apply Consistent Security Across VMs, Containers, and Bare Metal"</A></BR>
SAI1087BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI1087BU.mp4">How VMware IT Leveraged the VMware Service-Defined Firewall</A></BR>
SAI1164BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI1164BU.mp4">Practical Guide to Multi-layered Security in the SDDC</A></BR>
SAI1268BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI1268BU.mp4">Introduction to AppDefense</A></BR>
SAI1295BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI1295BU.mp4">Ensure Good App Behavior with AppDefense App Verification Cloud</A></BR>
SAI1452BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI1452BU.mp4">NSX Service-Defined Firewall Reference Architecture Deep Dive</A></BR>
SAI1529BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI1529BU.mp4">NSX-T Firewall Design and Deployment Best Practices</A></BR>
SAI1847BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI1847BU.mp4">Introduction to the VMware NSX Service-Defined Firewall</A></BR>
SAI1986BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI1986BU.mp4">Agentless Anti-Virus with NSX-T Guest Introspection Deep Dive</A></BR>
SAI2134BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI2134BU.mp4">Secure Your VMs with vSphere and AppDefense</A></BR>
SAI2565BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI2565BU.mp4">What's New with NSX-T Micro-Segmentation</A></BR>
SAI2781BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI2781BU.mp4">NSX-T Advanced Security and Networking Service Insertion Deep Dive</A></BR>
SAI2849BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI2849BU.mp4">Deploying AppDefense: Use Cases and Customer Examples</A></BR>
SAI3071BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI3071BU.mp4">Using VMware NSX Policy and Analytics to Address Key Challenges in Security</A></BR>
SAI3196BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI3196BU.mp4">AppDefense Reference Architecture Deep Dive</A></BR>
SAI3336BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI3336BU.mp4">Best Practices: Security and Compliance for Cloud Workloads</A></BR>
SAI3503BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI3503BUS.mp4">Best Practices for Architecting Hybrid Cloud Security</A></BR>
SAI3508BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI3508BUS.mp4">"Security Past, Present and Future ??? Securing your Evolving Infrastructure"</A></BR>
SAI3510BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI3510BUS.mp4">Healthy Expansion: CHRISTUS Health???s Virtualization Journey </A></BR>
SAI3673BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI3673BU.mp4">Analytics-driven Application Security and Web Application Firewall </A></BR>
SAI4118BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/SAI4118BU.mp4">Data Guardians of the Galaxy: Securing the Future of your Endpoints</A></BR>
T5G1105BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/T5G1105BU.mp4">Achieving High Performance with NFV Data Plane Workloads: The Secrets</A></BR>
T5G1731BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/T5G1731BU.mp4">Accelerating VMware vCloud NFV Delivery: A Case Study</A></BR>
T5G1919BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/T5G1919BU.mp4">Deploying VMware vCloud NFV Integrated OpenStack: A Step-by-Step Approach</A></BR>
T5G2264BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/T5G2264BU.mp4">Ericsson Virtual Packet Gateway on vCloud NFV: Cooperation and Optimization</A></BR>
T5G3863BUS<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/T5G3863BUS.mp4">Samsung Knox:  Evolution to Hyper-Connectivity</A></BR>
T5G3864BU<A HREF="https://s3-us-west-1.amazonaws.com/vmworld-usa-2019/T5G3864BU.mp4">Evolving your network with 5G and SD-WAN</A></BR>
